create or replace view rpt_crm_mart.v_wldn_loe_brand_profile as
select
   b.id as brand_profile_id,
   b.banner_id_c,
   b.first_name_c,
   b.last_name_c,
   b.middle_name_c,
   b.cbl_student_id_c,
   b.billing_address_c,
   b.billing_street_c,
   b.billing_street_2_c,
   b.billing_city_c,
   b.billing_state_text_c,
   b.billing_country_text_c,
   b.billing_postal_code_c,
   b.shipping_address_c,
   b.shipping_street_c,
   b.shipping_street_2_c,
   b.shipping_city_c,
   b.shipping_state_text_c,
   b.shipping_country_text_c,
   b.shipping_postal_code_c,
   b.preferred_address_c,
   b.home_phone_country_code_c,
   b.home_phone_c,
   b.mobile_phone_country_code_c,
   b.mobile_phone_c,
   b.work_phone_country_code_c,
   b.work_phone_c,
   b.preferred_phone_c,
   b.personal_email_c,
   b.preferred_email_c,
   b.university_email_c,
   b.alternate_email_c,
   b.system_modstamp,
   b.last_activity_date,
   b.last_modified_date,
   b.last_modified_by_id,
   b.created_date,
   b.created_by_id,
   b.is_deleted,
   b.salutation_c,
   b.gender_c,
   b.birthdate_c

from
   `raw_b2c_sfdc.brand_profile_c` b
where
   lower(b.institution_c) = 'a0ko0000002bsh4aao' and is_deleted = false
